In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stock_dataset.csv")

In [3]:
df

    stock_name        date    close  volume  daily_return
0     RELIANCE  2023-01-02  1023.45  359178           NaN
1     RELIANCE  2023-01-03  1028.19  237337      0.004631
2     RELIANCE  2023-01-04  1041.88  187498      0.013315
3     RELIANCE  2023-01-05  1044.67  378167      0.002678
4     RELIANCE  2023-01-06  1054.77  141090      0.009668
..         ...         ...      ...     ...           ...
775       HDFC  2023-12-25  1000.93  330662     -0.009725
776       HDFC  2023-12-26   998.69  476158     -0.002238
777       HDFC  2023-12-27  1001.98  163646      0.003294
778       HDFC  2023-12-28  1005.93  365798      0.003942
779       HDFC  2023-12-29  1015.42  305244      0.009434

[780 rows x 5 columns]

In [4]:
df.describe()

             close         volume  daily_return
count   780.000000     780.000000    777.000000
mean   1002.245628  298356.284615     -0.000051
std      56.631662  114118.456127      0.010630
min     860.850000  101015.000000     -0.032915
25%     961.607500  201660.500000     -0.007288
50%    1001.245000  293188.500000      0.000130
75%    1037.300000  394240.750000      0.007333
max    1169.370000  498992.000000      0.033251

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   stock_name    780 non-null    object
 1   date          780 non-null    object
 2   close         780 non-null    float64
 3   volume        780 non-null    int64
 4   daily_return  777 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 30.6+ KB

In [7]:
df.columns

Index(['stock_name', 'date', 'close', 'volume', 'daily_return'], dtype='object')

In [8]:
df.isnull().sum()

stock_name      0
date            0
close           0
volume          0
daily_return    3
dtype: int64

In [10]:
df['daily_return'] = df['daily_return'].fillna(0)

In [11]:
df.isnull().sum()

stock_name      0
date            0
close           0
volume          0
daily_return    0
dtype: int64

In [9]:
df['date'] = pd.to_datetime(df['date'])

In [12]:
df = df.sort_values(by='date')

In [13]:
df.duplicated().sum()

df = df.drop_duplicates()

In [14]:
df['daily_return'] = df['close'].pct_change()

In [15]:
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

In [17]:
df.describe()

,date,close,volume,daily_return,month,year
count,780,780.000000,780.000000,779.000000,780.000000,780.0
mean,2023-07-01 12:00:00.000000256,1002.245628,298356.284615,0.003674,6.507692,2023.0
min,2023-01-02 00:00:00,860.850000,101015.000000,-0.217266,1.000000,2023.0
25%,2023-04-02 06:00:00,961.607500,201660.500000,-0.051989,3.750000,2023.0
50%,2023-07-01 12:00:00,1001.245000,293188.500000,0.005593,6.500000,2023.0
75%,2023-09-29 18:00:00,1037.300000,394240.750000,0.055077,9.250000,2023.0
max,2023-12-29 00:00:00,1169.370000,498992.000000,0.308010,12.000000,2023.0
std,NaN,56.631662,114118.456127,0.086010,3.440108,0.0

In [18]:
df['daily_return'].describe()

count    779.000000
mean       0.003674
std        0.086010
min       -0.217266
25%       -0.051989
50%        0.005593
75%        0.055077
max        0.308010
Name: daily_return, dtype: float64

In [20]:
df['month'].describe()

count    780.000000
mean       6.507692
std        3.440108
min        1.000000
25%        3.750000
50%        6.500000
75%        9.250000
max       12.000000
Name: month, dtype: float64

In [21]:
df

    stock_name       date    close  volume  daily_return  month  year
0     RELIANCE 2023-01-02  1023.45  359178           NaN      1  2023
260    INFOSYS 2023-01-02  1021.27  342926     -0.002130      1  2023
520       HDFC 2023-01-02  1055.65  387654      0.033664      1  2023
1     RELIANCE 2023-01-03  1028.19  237337     -0.026012      1  2023
261    INFOSYS 2023-01-03  1016.58  212816     -0.011292      1  2023
..         ...        ...      ...     ...           ...    ...   ...
258   RELIANCE 2023-12-28   922.38  229473     -0.083057     12  2023
518    INFOSYS 2023-12-28  1087.58  442703      0.179102     12  2023
519    INFOSYS 2023-12-29  1098.11  304615      0.009682     12  2023
259   RELIANCE 2023-12-29   910.07  101015     -0.171240     12  2023
779       HDFC 2023-12-29  1015.42  305244      0.115760     12  2023

[780 rows x 7 columns]

In [22]:
df.head()

    stock_name       date    close  volume  daily_return  month  year
0     RELIANCE 2023-01-02  1023.45  359178           NaN      1  2023
260    INFOSYS 2023-01-02  1021.27  342926     -0.002130      1  2023
520       HDFC 2023-01-02  1055.65  387654      0.033664      1  2023
1     RELIANCE 2023-01-03  1028.19  237337     -0.026012      1  2023
261    INFOSYS 2023-01-03  1016.58  212816     -0.011292      1  2023

In [23]:
df['daily_return'] = df.groupby('stock_name')['close'].pct_change()

In [24]:
df.head()

    stock_name       date    close  volume  daily_return  month  year
0     RELIANCE 2023-01-02  1023.45  359178           NaN      1  2023
260    INFOSYS 2023-01-02  1021.27  342926           NaN      1  2023
520       HDFC 2023-01-02  1055.65  387654           NaN      1  2023
1     RELIANCE 2023-01-03  1028.19  237337      0.004631      1  2023
261    INFOSYS 2023-01-03  1016.58  212816     -0.004592      1  2023

In [25]:
df['daily_return'] = df['daily_return'].fillna(0)

In [26]:
df.head()

    stock_name       date    close  volume  daily_return  month  year
0     RELIANCE 2023-01-02  1023.45  359178      0.000000      1  2023
260    INFOSYS 2023-01-02  1021.27  342926      0.000000      1  2023
520       HDFC 2023-01-02  1055.65  387654      0.000000      1  2023
1     RELIANCE 2023-01-03  1028.19  237337      0.004631      1  2023
261    INFOSYS 2023-01-03  1016.58  212816     -0.004592      1  2023

In [27]:
df.groupby('stock_name')['daily_return'].head(3)

0      0.000000
260    0.000000
520    0.000000
1      0.004631
261   -0.004592
521    0.012855
2      0.013315
262    0.013506
522   -0.025374
Name: daily_return, dtype: float64

In [28]:
df.groupby('stock_name')['daily_return'].mean()

stock_name
HDFC       -0.000085
INFOSYS     0.000335
RELIANCE   -0.000404
Name: daily_return, dtype: float64

In [29]:
df.groupby('stock_name')['daily_return'].std()

stock_name
HDFC        0.011413
INFOSYS     0.010619
RELIANCE    0.009761
Name: daily_return, dtype: float64

In [30]:
df.groupby('stock_name')['close'].agg(['min','max'])

               min      max
stock_name
HDFC        860.85  1073.85
INFOSYS     944.75  1169.37
RELIANCE    910.07  1057.22

In [31]:
df.head()

    stock_name       date    close  volume  daily_return  month  year
0     RELIANCE 2023-01-02  1023.45  359178      0.000000      1  2023
260    INFOSYS 2023-01-02  1021.27  342926      0.000000      1  2023
520       HDFC 2023-01-02  1055.65  387654      0.000000      1  2023
1     RELIANCE 2023-01-03  1028.19  237337      0.004631      1  2023
261    INFOSYS 2023-01-03  1016.58  212816     -0.004592      1  2023

In [32]:
save = df.to_csv("clean_stock_data.csv", index=False)
save